### ISSUE TITLE
DO-3 | wykresy

### ISSUE THREAD

**Issue by Rolkarolka** [Rolkarolka/IUM-delivery-optimization#2]
Jaki wykres jest tworzony

**Comment by Rolkarolka** [comment]
- [x] ilość zamówień w danym miesiącu

**Comment by ERoszczyk** [comment]
- [x] ilość zamówień z danej kategorii

**Comment by ERoszczyk** [comment]
- [x] ilość zamówień w danych przedziałach cenowych

**Comment by ERoszczyk** [comment]
- [x] aktywność użytkowników w danym miesiącu (czasie)

**Comment by ERoszczyk** [comment]
- [x] ilość zamówień w zależności od promocji

**Comment by ERoszczyk** [comment]
- [x] ilość zamówień w zależności od ilości wyświetleń danego produktu

**Comment by Rolkarolka** [comment]
- [ ] ilość zamówień w zależności od ceny po promocji

**Comment by Rolkarolka** [comment]
- [ ] ilość zamówień w zależności od promocji biorąc po uwagę kategorię
